### ISSUE TITLE
How configure dsym URL?

### ISSUE THREAD

**Issue by patsevanton** [sentry-demos/android#141]
Hello! Thanks for sentry-demos!

I put dsn token to auth.token in sentry.properties
after make all get error
```
2024-07-17 20:49:06.199950147 +06:00 request POST https://sentry.io/api/0/projects/demo/android/files/dsyms/
2024-07-17 20:49:07.319839569 +06:00 < HTTP/1.1 401 Unauthorized
```
How configure dsym URL?

**Comment by sdzhong** [comment]
Hey @patsevanton , sorry about the trouble with getting started with this repo. The steps in https://github.com/sentry-demos/android?tab=readme-ov-file#setup should be followed by a Sentry employee for their Sentry demo; this app isn't designed to be functional for the public. Please check out https://github.com/getsentry/sentry-java?tab=readme-ov-file#samples instead.
