### ISSUE TITLE
checkout [android] transaction span has incorrectly associated SentryHttpClientException: HTTP Client Error with status code: 500 error

### ISSUE THREAD

**Issue by sdzhong** [sentry-demos/android#60]
**Problem for branch [perf-issues-db_main_thread](https://github.com/sentry-demos/android/tree/perf-issues-db_main_thread) at [this commit](https://github.com/sentry-demos/android/tree/f193e9834ca096c73d0bde23b4058ff6978c16c8):**
The [checkout [android] transaction](https://testorg-az.sentry.io/performance/mobile-android:8d68f91637034196b321b817c0a9c115/?transaction=checkout+%5Bandroid%5D) has span `http.client.connection`, which is incorrectly associated with [SentryHttpClientException: HTTP Client Error with status code: 500](https://testorg-az.sentry.io/issues/4325187142/events/81fb6192c80146b096bf14786b60e1bb/?project=1801383/) error. The span’s Status is `deadline_exceeded`, but this is not accurate. The error should not be due to the http client connection nor deadline--it is due to [an associated backend error](https://testorg-az.sentry.io/issues/4133546415/events/844b41e396fd4152beb061a18efe6697/?project=5808655).
![image](https://github.com/sentry-demos/android/assets/89550162/211f0107-1b2e-459f-89cb-9d655fe1459a)

**Expected Behavior:**
Error should to match with current [checkout [android]](https://testorg-az.sentry.io/performance/mobile-android:be110a87a92647b2a9078f189b6c1c73/?transaction=checkout+%5Bandroid%5D), where it has an `http.client` span with associated error [SentryHttpClientException: HTTP Client Error with status code: 500](https://testorg-az.sentry.io/issues/4229688858/events/4f86fb443cce40fb8c835236ac73ce16/). The span’s Status is `internal_error`.
![image](https://github.com/sentry-demos/android/assets/89550162/3aecc417-d46b-42cd-a457-e44156880aab)

**Comment by sdzhong** [comment]
I attempted to [disable the OkHttp instrumentation feature](https://docs.sentry.io/platforms/android/configuration/integrations/okhttp/#disable) to see if that would change behavior, but it did not. [The resulting transaction](https://testorg-az.sentry.io/discover/mobile-android:25f11d66478741c0a70b6f4d3ea150ae/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=1801383&query=sdk.version%3A6.22.0&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29) shows `Missing span instrumentation`, but http.client spans still appear. 

Are steps to disable the disable the OkHttp instrumentation feature correct?

**Comment by stefanosiano** [comment]
this should be fixed with the version in master. It will be published in a new release

**Comment by sdzhong** [comment]
Available in v6.28 of Java SDK https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md#6280

**Comment by sdzhong** [comment]
1. Update plugin to 3.12.0: [commit](https://github.com/sentry-demos/android/commit/44bb6a5532eebed22e285d0b852d328910a18c33)
2. Produced events: [discover query](https://testorg-az.sentry.io/discover/results/?end=2023-08-29T02%3A46%3A59&field=title&field=release&field=environment&field=user.display&field=timestamp&field=sdk.version&name=MainFragment%24BackendAPIException%3A+Failed+to+init+delivery+workflow&project=1801383&query=sdk.version%3A6.28.0&sort=-timestamp&start=2023-08-29T02%3A29%3A08&yAxis=count%28%29)

[The checkout [android] transaction](https://testorg-az.sentry.io/discover/mobile-android:e6541eed5b984fe2bf1786ffca82acd0/?end=2023-08-29T02%3A46%3A59.000&field=title&field=release&field=environment&field=user.display&field=timestamp&field=sdk.version&name=MainFragment%24BackendAPIException%3A+Failed+to+init+delivery+workflow&project=1801383&query=sdk.version%3A6.28.0&sort=-timestamp&start=2023-08-29T02%3A29%3A08.000&yAxis=count%28%29) appears unchanged: the associated error is still appearing on `http.client.connection` with status `deadline_exceeded`.
![image](https://github.com/sentry-demos/android/assets/89550162/09964bb0-b5ad-4e63-ad7c-98b3e20eb18b)

**Comment by sdzhong** [comment]
@stefanosiano , please take a look at the SDK code and let me know.

**Comment by stefanosiano** [comment]
we ended up reporting a [new issue](https://github.com/getsentry/sentry-java/issues/2908)
The problem happens when not closing the response of the http call. Adding `response.close()` fixed it.
I already updated the code with the change.
@sdzhong Can you validate again?

**Comment by sdzhong** [comment]
Hey @stefanosiano, I believe [your commit](https://github.com/sentry-demos/android/commit/710edb179359d8a33fc5f6c8e5fa95a066f205ad) is good in resolving the span’s Status to show `internal_error` instead of `deadline_exceeded`. (reference [event](https://testorg-az.sentry.io/discover/mobile-android:8515f336a176402b96b3a6802e486d9b/?end=2023-08-30T19%3A49%3A54.000&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=1801383&query=sdk.version%3A6.28.0&sort=-timestamp&start=2023-08-30T19%3A47%3A01.000&yAxis=count%28%29))

During my validation, I noticed that there are several regressions related to the Flagship Error `MainFragment$BackendAPIException` perhaps related to another change--updating Sentry gradle plugin v to 3.12.0 ([commit](https://github.com/sentry-demos/android/commit/44bb6a5532eebed22e285d0b852d328910a18c33))--I will gather them and share.

**Comment by sdzhong** [comment]
Simon to validate

**Comment by sdzhong** [comment]
✅ Validated in tests with branch https://github.com/sentry-demos/android/tree/version/30, [checkout [android]](https://demo.sentry.io/performance/mobile-android:8635401f3b774146a70f094c2e904104/?project=1801383&transaction=checkout+%5Bandroid%5D).

**Comment by sdzhong** [comment]
Hey @stefanosiano, can you please comment on:

> The [checkout [android] transaction](https://testorg-az.sentry.io/performance/mobile-android:8d68f91637034196b321b817c0a9c115/?transaction=checkout+%5Bandroid%5D) has span http.client.connection, which is incorrectly associated with [SentryHttpClientException: HTTP Client Error with status code: 500](https://testorg-az.sentry.io/issues/4325187142/events/81fb6192c80146b096bf14786b60e1bb/?project=1801383/) error

![Image](https://github.com/sentry-demos/android/assets/89550162/45ae3ac6-189e-4a92-9d00-50823076c72d)

I believe the Android `SentryHttpClientException: HTTP Client Error with status code: 500` error doesn't have to do with an/the HttpClient _connection_--the `http.client.connection` span--per se; more to do with its parent `http.client` span (which was the association previously).

![Image](https://github.com/sentry-demos/android/assets/89550162/88b7f3ba-1d27-4eb6-9be5-58babc844b1b)


Can you please share your thoughts on whether the `SentryHttpClientException: HTTP Client Error with status code: 500` should be associated with the `http.client.connection` span, or if it should be associated with its parent `http.client` span as it was before?
P.S. this is a recently generated [checkout [android]](https://demo.sentry.io/performance/mobile-android:8635401f3b774146a70f094c2e904104/?project=1801383&transaction=checkout+%5Bandroid%5D) transaction, generated from https://github.com/sentry-demos/android/tree/version/30.

**Comment by stefanosiano** [comment]
Technically, it happens in the connection phase, so i guess it would be more correct to be there, but no real preference

**Comment by sdzhong** [comment]
We determined it's worth getting a second opinion about where--which span--the error is most appropriate: the `http.client.connection span` it's in now, or its parent `http.client` span.

![Image](https://github.com/sentry-demos/android/assets/89550162/73195d97-a4ab-4cf8-8d26-a1bc7e32819c)

@stefanosiano to start the conversation internally with mobile team.

**Comment by sdzhong** [comment]
The mobile team determined that we should have the error associated with the `http.client` span.

**Comment by sdzhong** [comment]
The updates are in review on the SDK-side https://github.com/getsentry/sentry-java/pull/2961/. The new release of the Android SDK should cover this.

**Comment by sdzhong** [comment]
@stefanosiano to update Android Gradle Plugin to 3.13.0 and retry.

**Comment by kahest** [comment]
https://github.com/sentry-demos/android/pull/88

**Comment by sdzhong** [comment]
Verified completed with #88: 

Error associated with `http.client` span
![Image](https://github.com/sentry-demos/android/assets/89550162/b8f06d24-0ec4-4da5-8f8a-5c36c33de951)



`http.client` span's Status is `internal_error`
![Image](https://github.com/sentry-demos/android/assets/89550162/add1b184-02ea-4863-b689-3b3f3143708e)
