### ISSUE TITLE
Create N+1 API Call Performance Issue

### ISSUE THREAD

**Issue by sdzhong** [sentry-demos/android#61]
**Problem for [branch perf-issues-db_main_thread-np1_api](https://github.com/sentry-demos/android/tree/perf-issues-db_main_thread-np1_api) (at [this commit](https://github.com/sentry-demos/android/tree/2b7b846da18a26a166e7b499eabb0bff102c8a5b)):**
Unable to make synchronous API calls to create [N+1 API Calls performance issue](https://docs.sentry.io/product/issues/issue-details/performance-issues/n-one-api-calls/). I've made two unsuccessful attempts: [[1]](https://github.com/sentry-demos/android/commit/2ec864b7ddce9de7e142939dc715c1632aaca883), [[2]](https://github.com/sentry-demos/android/commit/2b7b846da18a26a166e7b499eabb0bff102c8a5b).

**Goal:**
Create a transaction to match this reference [React /nplusone transaction](https://testorg-az.sentry.io/performance/frontend-javascript:d530470d7b6c40f49dec434d06dcd763/), which generates this [N+1 API Call performance issue](https://testorg-az.sentry.io/issues/3952653497/?project=5808623&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0). 
The attempts so far have been by using [this button](https://github.com/sentry-demos/android/blob/2b7b846da18a26a166e7b499eabb0bff102c8a5b/app/src/main/res/layout/activity_main.xml#L157-L166) to [trigger the API calls](https://github.com/sentry-demos/android/blob/2b7b846da18a26a166e7b499eabb0bff102c8a5b/app/src/main/java/com/example/vu/android/MainActivity.java#L99-L121):
![image](https://github.com/sentry-demos/android/assets/89550162/25e064a0-7f2e-4741-ad26-2f833745dd56)

**Comment by stefanosiano** [comment]
this should work out of the box with version `7.0.0` of the Android SDK (not yet available)

**Comment by sdzhong** [comment]
Hey @stefanosiano, I see that the [Android SDK version 7.0.0](https://github.com/getsentry/sentry-java/releases/tag/7.0.0) is now available. May we move this out of Todo?

**Comment by sdzhong** [comment]
Update: We would want the `N+1 API Calls` perf issue to be in the flagship transaction **EmpowerPlantActivity** (not the `checkout [android]` transaction, which I was testing in the original post).
