### ISSUE TITLE
Standardise exception name for flagship error

### ISSUE THREAD

**Issue by realkosty** [sentry-demos/android#68]
Right now we are using `MainFragment$ItemDeliveryProcessException`
TBD what will be standard name for flagship exception across all platforms?
Please comment what you would use for a backend API exception in a real Android app according to Android conventions and common practices?
For now can use `BackendAPIException` - better than current

Update: Karl mentioned that on mobile platforms exceptions names can be idiomatic and specific to platform. Let's find some middle ground to make it recognizable for SE while looking "normal" for the platform

**Comment by sdzhong** [comment]
MainFragment$BackendAPIException works for me

**Comment by sdzhong** [comment]
WIP https://github.com/sentry-demos/android/pull/73

**Comment by sdzhong** [comment]
https://github.com/sentry-demos/android/pull/73
