### ISSUE TITLE
Create Flagship Profile

### ISSUE THREAD

**Issue by sdzhong** [sentry-demos/android#69]
Docs reference: https://docs.sentry.io/platforms/android/profiling/

[Profiling is enabled](https://github.com/sentry-demos/android/blob/1bf3732467c3b5ffeaf87d5ee21c6cdb03da4804/app/src/main/AndroidManifest.xml#L70C1-L75).
Set up a function for a problem to solve.

**Comment by sdzhong** [comment]
Goal is to show slow cold start with slow span with slow function (seen in its profile).

**Comment by sdzhong** [comment]
Simon to validate PR #76

**Comment by sdzhong** [comment]
Tested locally and noticed that frames are not appearing for EmpowerPlantActivity transaction’s span `product_processing` as expected (e.g. [this profile](https://demo.sentry.io/profiling/profile/mobile-android/82159e9641e44da49c1d2738b8d05055/flamegraph/?colorCoding=by+recursion&query=&sorting=call+order&spanId=cb96cf8320894979&tid=17317&view=top+down)). This may be due to a hard deadline of 30s. 

I am checking about configurability of this deadline.

**Comment by sdzhong** [comment]
Configurability of the aforementioned 30s deadline is not a blocker, since the profile appears when generating events via pytest `sentry-demos/empower/tda/mobile_native/android/test_checkout_android.py` (the EmpowerPlantActivity transaction consistently takes ~25s).

However, the profile names do not match what is expected from https://github.com/sentry-demos/android/pull/76:




![Image](https://github.com/sentry-demos/android/assets/89550162/94ac2931-d0dd-4d23-9ac3-664cb234dbca)

**Comment by stefanosiano** [comment]
regarding the name, something is wrong with the proguard configuration via pytest. Maybe it builds the app without the auth token?

**Comment by sdzhong** [comment]
> regarding the name, something is wrong with the proguard configuration via pytest. Maybe it builds the app without the auth token?


We reviewed the way the .apk's are getting generated (https://github.com/sentry-demos/android/blob/master/generate_release_artifacts.sh, where my local sentry.properties [where I run `generate_release_artifacts.sh`] contains a valid auth token). @stefanosiano to take a closer look

**Comment by stefanosiano** [comment]
before committing the change, i have a question, just to be sure.
Did anyone change the org name from `testorg-az` to `demo`?
If so, just changing it in the sentry.properties file will make proguard mapping working fine again

**Comment by stefanosiano** [comment]
The org name was changed from `testorg-az` to `demo` in master.
I updated the `feat/flagship-profile` and `feat/profiling-issues` branches with the latest changes in master and proguard mappings are uploaded now.
Can we check if the `Always suggest updating pull request branches` option in Settings -> General -> Pull Requests is enabled in this Github repo?

**Comment by sdzhong** [comment]
> Can we check if the Always suggest updating pull request branches option in Settings -> General -> Pull Requests is enabled in this Github repo?

It was not enabled. I've just enabled it.

**Comment by sdzhong** [comment]
RE: https://github.com/sentry-demos/android/issues/69#issuecomment-1724171392, where profile names generated don't have the function name
The function name is not symbolicated in the profile and so this is a known issue and limitation of the current Android Profiler.

**Comment by stefanosiano** [comment]
There is an update for the backend: https://github.com/getsentry/rust-proguard/pull/30
This should fix all the function names in the Android profiles that are not ambiguous (it doesn't cover the case of 2 methods with the same name but different parameters).
However, this should handle most cases.

**Comment by sdzhong** [comment]
Fixed in a backend update--the [Flagship Transaction’s Profile](https://demo.sentry.io/profiling/profile/android/a32901c3aa0542a5ba15958bb5ca43d4/flamegraph/?colorCoding=by+recursion&fov=10007764992%2C30%2C1046852608%2C12&query=&sorting=call+order&spanId=da4484f0fd4e4203&tid=5466&view=top+down) now shows `getIterator(int)` function name


![Image](https://github.com/sentry-demos/android/assets/89550162/cfef3cd0-a888-4b1c-8c73-99c9965e4395)
