### ISSUE TITLE
Reduce time of mock functions in EmpowerPlantActivity transaction

### ISSUE THREAD

**Issue by sdzhong** [sentry-demos/android#82]
Running the app locally can cause slower performance. The slower performance can hit unintended deadlines. E.g. there is a hard deadline (of 30s) when capturing profiles.

![image](https://github.com/sentry-demos/android/assets/89550162/fc75df13-b7d3-4a24-9cfb-84d61b012a57)

Reducing time of mock functions to avoid deadline(s) will allow for testing/validating the app locally.

Note: This is not a problem when generating events via pytests (i.e. https://github.com/sentry-demos/empower/blob/master/tda/mobile_native/android/test_checkout_android.py generates EmpowerPlantActivity transactions of ~25s).

**Comment by kahest** [comment]
PR for this: https://github.com/sentry-demos/android/pull/89
