### ISSUE TITLE
Create GitHub Release Workflow

### ISSUE THREAD

**Issue by sdzhong** [sentry-demos/android#92]
Create GitHub release workflow like what was set up for [sentry-demos/ios](https://github.com/sentry-demos/ios): 
https://github.com/sentry-demos/ios/actions/workflows/release.yml > `Run workflow`, see screenshot
![image](https://github.com/sentry-demos/android/assets/89550162/c8abd936-6378-4508-9c0e-b16b65f01563)

Context:
1. https://github.com/sentry-demos/ios/blob/master/.github/workflows/release.yml
2. https://github.com/sentry-demos/ios/actions
3. https://github.com/sentry-demos/ios/issues?q=ci%3A

**Comment by sdzhong** [comment]
Kosty mentioned:

> Let’s sync/hold off before you do any more work in this direction
> We will be moving the repo into empower repo and changing how TDA works and those things will have implications for releases.

Moving back to `Todo` status

**Comment by ndmanvar** [comment]
@sdzhong - can we get the devs to help us with this one next? 🙏 
Once this gets done..then we don't have to rely on local setups / build+releases at all.

**Comment by stefanosiano** [comment]
@sdzhong 
PR is ready. Have a look at my [comment](https://github.com/sentry-demos/android/pull/117#issuecomment-1904652985)

**Comment by sdzhong** [comment]
Details about validation & functionality [here](https://github.com/sentry-demos/android/pull/124#pullrequestreview-1849995485)
